version: '3'

services:

  web:
    build:
      context: .
    env_file:
      - ./src/.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
